<x-admin.layouts.app title="Rekap Absensi">
    <div class="space-y-6">
        <div class="flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-medium text-[#8A94A6]">Ringkasan per peserta</p><h2 class="mt-1 font-heading text-2xl font-bold text-[#0C2340]">Rekap Absensi</h2></div><p class="text-xs text-[#8A94A6]">Senin–Jumat dihitung sebagai hari kerja.</p></div>

        <x-admin.card>
            <form method="GET" class="grid gap-3 lg:grid-cols-[minmax(0,1.5fr)_repeat(2,minmax(0,1fr))_auto] lg:items-end"><div><label class="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-[#8A94A6]">Peserta Magang</label><select name="intern_id" class="w-full rounded-lg border border-[#E3E5DE] px-3 py-2.5 text-sm focus:border-[#0C2340] focus:outline-none focus:ring-1 focus:ring-[#0C2340]"><option value="">Semua peserta</option>@foreach ($interns as $intern)<option value="{{ $intern->id }}" @selected($selectedIntern?->id === $intern->id)>{{ $intern->name }} · {{ $intern->username }}</option>@endforeach</select></div><div><label class="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-[#8A94A6]">Mulai</label><input type="date" name="start_date" value="{{ $periodStart }}" class="w-full rounded-lg border border-[#E3E5DE] px-3 py-2.5 text-sm"></div><div><label class="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-[#8A94A6]">Selesai</label><input type="date" name="end_date" value="{{ $periodEnd }}" class="w-full rounded-lg border border-[#E3E5DE] px-3 py-2.5 text-sm"></div><div class="flex gap-2"><button class="flex-1 rounded-lg bg-[#0C2340] px-4 py-2.5 text-sm font-semibold text-white">Tampilkan</button><a href="{{ route('admin.attendance.recap') }}" class="rounded-lg border border-[#E3E5DE] px-4 py-2.5 text-sm font-semibold text-[#687386]">Reset</a></div></form>
            @if ($selectedIntern)<div class="mt-4 rounded-lg bg-[#E8EEF5] px-4 py-3 text-sm text-[#0C2340]">Periode <strong>{{ $selectedIntern->name }}</strong>: {{ $periodStart }} sampai {{ $periodEnd }}.</div>@endif
        </x-admin.card>

        <x-admin.card title="Absensi Hari Ini" subtitle="Data akan diperbarui otomatis setiap 60 detik.">
            <div class="mb-4 flex items-center justify-between rounded-lg bg-[#E8EEF5] px-4 py-3 text-sm text-[#0C2340]"><span>{{ now()->translatedFormat('l, d F Y') }}</span><span class="text-xs font-semibold">{{ $todayRecords->count() }} peserta sudah scan</span></div>
            <div class="responsive-table"><table class="w-full min-w-[700px] text-left text-sm"><thead><tr class="border-b border-[#E7EAF1] text-xs uppercase tracking-wide text-[#8A94A6]"><th class="py-3 pr-4">Mahasiswa</th><th class="py-3 pr-4">Datang</th><th class="py-3 pr-4">Pulang</th><th class="py-3 pr-4">Status</th><th class="py-3 pr-4">Lokasi</th></tr></thead><tbody class="divide-y divide-[#EEF0F5]">@forelse ($todayRecords as $record)<tr><td class="py-3 pr-4"><p class="font-medium text-[#1E2A24]">{{ $record->intern->name }}</p><p class="text-xs text-[#8A94A6]">{{ $record->intern->username }}</p></td><td class="py-3 pr-4 font-medium">{{ $record->check_in_at?->format('H:i') ?? '-' }}</td><td class="py-3 pr-4">{{ $record->check_out_at?->format('H:i') ?? '-' }}</td><td class="py-3 pr-4"><span class="rounded-full bg-[#E8EEF5] px-2.5 py-1 text-xs font-semibold text-[#0C2340]">{{ $record->check_in_status ? ucwords(str_replace('_', ' ', $record->check_in_status)) : '-' }}</span></td><td class="py-3 pr-4 text-xs text-[#687386]">{{ $record->check_in_distance_meters !== null ? $record->check_in_distance_meters.' m' : 'Belum ada' }}</td></tr>@empty<tr><td colspan="5" class="py-8 text-center text-sm text-[#8A94A6]">Belum ada mahasiswa yang scan hari ini.</td></tr>@endforelse</tbody></table></div>
        </x-admin.card>

        <div class="grid grid-cols-2 gap-4 xl:grid-cols-4">@foreach ([['label'=>'Total Hari Kerja','value'=>$summary['total'],'accent'=>'border-[#0C2340]'],['label'=>'Hadir','value'=>$summary['hadir'],'accent'=>'border-emerald-500'],['label'=>'Perlu Verifikasi','value'=>$summary['pending'],'accent'=>'border-amber-500'],['label'=>'Izin + Sakit','value'=>$summary['leave_pending'],'accent'=>'border-blue-500']] as $item)<div class="rounded-xl border-l-4 {{ $item['accent'] }} bg-white p-4 shadow-sm"><p class="font-heading text-2xl font-bold text-[#0C2340]">{{ $item['value'] }}</p><p class="mt-1 text-xs font-medium text-[#8A94A6]">{{ $item['label'] }}</p></div>@endforeach</div>

        <x-admin.card title="Ringkasan Kehadiran Per Orang" subtitle="Alpa dihitung dari hari kerja yang belum memiliki hadir, izin, atau sakit yang disetujui.">
            <div class="responsive-table"><table class="w-full min-w-[980px] text-left text-sm"><thead><tr class="border-b border-[#E7EAF1] text-xs uppercase tracking-wide text-[#8A94A6]"><th class="py-3 pr-4">Peserta</th><th class="py-3 pr-4">Periode Magang</th><th class="py-3 pr-4 text-center">Hari Kerja</th><th class="py-3 pr-4 text-center">Hadir</th><th class="py-3 pr-4 text-center">Terlambat</th><th class="py-3 pr-4 text-center">Izin</th><th class="py-3 pr-4 text-center">Sakit</th><th class="py-3 pr-4 text-center">Alpa</th><th class="py-3 pr-4 text-center">Verifikasi</th></tr></thead><tbody class="divide-y divide-[#EEF0F5]">@forelse ($summaryRows as $row)<tr class="hover:bg-[#F8FAFD]"><td class="py-4 pr-4"><p class="font-semibold text-[#1E2A24]">{{ $row['intern']->name }}</p><p class="text-xs text-[#8A94A6]">{{ $row['intern']->username }} · {{ $row['intern']->university }}</p></td><td class="py-4 pr-4 text-xs text-[#687386]">{{ $row['period_start'] }}<br>s/d {{ $row['period_end'] }}</td><td class="py-4 pr-4 text-center font-medium text-[#1E2A24]">{{ $row['working_days'] }}</td><td class="py-4 pr-4 text-center"><span class="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-semibold text-emerald-700">{{ $row['present'] }}</span></td><td class="py-4 pr-4 text-center text-[#8A94A6]">{{ $row['late'] }}</td><td class="py-4 pr-4 text-center"><span class="rounded-full bg-blue-100 px-2.5 py-1 text-xs font-semibold text-blue-700">{{ $row['izin'] }}</span></td><td class="py-4 pr-4 text-center"><span class="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-semibold text-amber-700">{{ $row['sakit'] }}</span></td><td class="py-4 pr-4 text-center"><span class="rounded-full bg-rose-100 px-2.5 py-1 text-xs font-semibold text-rose-700">{{ $row['alpha'] }}</span></td><td class="py-4 pr-4 text-center text-xs text-[#8A94A6]">{{ $row['pending'] }}</td></tr>@empty<tr><td colspan="9" class="py-10 text-center text-sm text-[#8A94A6]">Belum ada peserta aktif.</td></tr>@endforelse</tbody></table></div>
        </x-admin.card>
    </div>
    @push('scripts')
        <script>setTimeout(() => window.location.reload(), 60000);</script>
    @endpush
</x-admin.layouts.app>
